package com.koakh.androidrealmobjectserverstartup.model;

import java.util.Calendar;
import java.util.Date;
import java.util.UUID;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

public class User extends RealmObject {

  @PrimaryKey
  private String  id = UUID.randomUUID().toString();
  private String name;
  private int age;
  private Date date = new Date(java.text.DateFormat.getDateTimeInstance().format(Calendar.getInstance().getTime()));

  @Ignore
  private int sessionId;

  // Standard getters & setters generated by your IDE…

  public String  getId() { return id; }
  public void setId(String  id) { this.id = id; }
  public String getName() { return name; }
  public void setName(String name) { this.name = name; }
  public int getAge() { return age; }
  public void setAge(int age) { this.age = age; }
  public int getSessionId() { return sessionId; }
  public void setSessionId(int sessionId) { this.sessionId = sessionId; }
}
